apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-traefik-ingress
  namespace: team-riker
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  guestbook-ui
                port:
                  number: 80
