apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: sample-xplane-aws-s3-bucket
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: "<ENTER_YOUR_NEW_BUCKET_NAME>"
spec:
  forProvider:
    locationConstraint: "<ENTER_YOUR_REGION>"  # choose your own region
    acl: private
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
  providerConfigRef:
    name: aws-provider-config
