apiVersion: s3.aws.jet.crossplane.io/v1alpha2
kind: Bucket
metadata:
  name: xplane-jet-aws-s3-bucket
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: "<ENTER_YOUR_NEW_BUCKET_NAME>"
spec:
  forProvider:
    region: "<ENTER_YOUR_REGION>"  # choose your own region
    acl: private
    tags:
      Name: "<ENTER_YOUR_NEW_BUCKET_NAME>"
  providerConfigRef:
    name: jet-aws-provider-config
