name: e2e-terratest

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.yml'
      - '**.yaml'
      - 'test/*'
  workflow_dispatch:

concurrency: e2e-terratest

jobs:
  test:
    name: Run E2E Terratest
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Setup Dependencies
        working-directory: test/src
        run: go get -v -t -d && go mod tidy -compat=1.17

      - name: Run Go E2E Tests
        working-directory: test/src
        run: go test -v -timeout 60m -tags=e2e
